"""add hackathons table

Revision ID: 48e2d1e1bb40
Revises: 68afa5106e81
Create Date: 2026-07-19 12:22:47.257201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e2d1e1bb40'
down_revision: Union[str, Sequence[str], None] = '68afa5106e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(length=50), nullable=True),
    sa.Column('eligibility_reason', sa.String(length=200), nullable=True),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_hackathons_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hackathons')
    # ### end Alembic commands ###
